name: unreal_whatsapp
description: A Very Good compatitor for whatsapp.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^3.5.1
  country_picker: ^2.0.15

  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_contacts: ^1.1.5
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.8.6
  intl: ^0.17.0
  permission_handler: ^10.1.0
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/backgroundImage.png
    - assets/bg.png
    - assets/default_user_profile_pic.png
