name: chatup
description: A Very Good chating app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.0.3
  country_picker: ^2.0.16

  firebase_app_check: ^0.1.1+5
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_contacts: ^1.1.5+1
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  permission_handler: ^10.2.0
  uuid: ^3.0.6
  visibility_detector: ^0.3.3

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/backgroundImage.png
    - assets/bg.png
    - assets/default_user_profile_pic.png
