// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUabafU3vl-rmWD-CDZ1cr9CEV-Na9Bo8',
    appId: '1:594052844146:android:aae70a0f514f5ed1c1d0eb',
    messagingSenderId: '594052844146',
    projectId: 'unreal-whatsapp-backend',
    storageBucket: 'unreal-whatsapp-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiaFRvrHOmTbS04uNWDVvpSQJwpsmpZx8',
    appId: '1:594052844146:ios:82b11438c44c0da1c1d0eb',
    messagingSenderId: '594052844146',
    projectId: 'unreal-whatsapp-backend',
    storageBucket: 'unreal-whatsapp-backend.appspot.com',
    androidClientId:
        '594052844146-unfqvr3u8k8i4s6281h5fnfaekfepef2.apps.googleusercontent.com',
    iosClientId:
        '594052844146-edqukeeklmkmam5ffhch61v6chei94vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.unreal-whatsapp',
  );
}
