on:
  pull_request:
    branches:
      - master
      - production
  push:
    branches:
      - master
      - production
name: "unreal whatsapp"
jobs:
  build:
    name: unreal whatsapp
    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.3'
      - run: flutter pub get
      # - run: flutter test
      - run: echo $KEYSTORE_BASE64 | base64 -D  -o $RUNNER_TEMP/release.keystore
      - run: pwd | ls
      - run: echo $KEYSTORE_BASE64 | base64 -D  -o release.keystore
      - run: pwd | ls
      - run: cd $RUNNER_TEMP pwd | ls
      # - run: flutter build apk --flavor production --release --split-per-abi
      # - run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload
      # - run: rm $RUNNER_TEMP/release.keystore
      # - run: rm release.keystore
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          # token: ${{ secrets.TOKEN }}
