on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "BETA"
jobs:
  build:
    name: BETA
    env:
      KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
      CHATUP_RELEASE_KEYSTORE_PATH: ${{secrets.CHATUP_RELEASE_KEYSTORE_PATH}}
      RELEASE_KEYSTORE_ALIAS: ${{secrets.RELEASE_KEYSTORE_ALIAS}}
      RELEASE_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{secrets.RELEASE_KEYSTORE_PRIVATE_KEY_PASSWORD}}
      RELEASE_KEYSTORE_PASSWORD: ${{secrets.RELEASE_KEYSTORE_PASSWORD}}
      GIPHY_API_KEY: ${{secrets.GIPHY_API_KEY}}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.3'
      - run: echo $KEYSTORE_BASE64 | base64 -D  -o $RUNNER_TEMP/release.keystore
      - run: flutter pub get
      - run: flutter build apk --flavor production --release --split-per-abi --dart-define=GIPHY_API_KEY=$GIPHY_API_KEY
      # - run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload
      - run: cd $RUNNER_TEMP && rm release.keystore
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v0.0.${{ github.run_number }}-beta
